extends:
  - google
  - 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  require-jsdoc:
    - warn
